editprofiledetails
Emilkroldrup/MinKostPlan pull request #28
Opened 2024-05-18 20:30 UTC by Mads505m

Den en er funktionel nu. Frontend skal bare laves om

2024-05-18 22:49 UTC, Spi0nDK approved these changes

2024-05-18 23:16 UTC, Emilkroldrup requested changes

2024-05-18 23:16 UTC, Emilkroldrup commented on src/main/java/minkostplan/application/DBcontroller/user/UserRepositoryImpl.java
> +            String sql = "UPDATE users SET username = COALESCE(?, username), email = COALESCE(?, email) WHERE email =?";
Skal man kun kunne edit username og email? hvad med vægt, højde, mål osv, man indtaster i surveyen?

2024-05-18 23:16 UTC, Emilkroldrup commented on src/main/java/minkostplan/application/UIcontroller/ProfilepageController.java
> +        System.out.println("User" + user);
Husk og fjern dette, når det er testet og klar til pr

2024-05-18 23:16 UTC, Emilkroldrup commented on src/main/java/minkostplan/application/UIcontroller/ProfilepageController.java
Vi skal helst ikke have for mange souts, så hellere lav javadoc på det og lav en unit test der tester

2024-05-18 23:16 UTC, Emilkroldrup commented on src/main/resources/templates/profilePage.html
Denne mangler bare styling og de nye felter, da du mangler og merge med develop, tror jeg.

2024-05-19 11:42 UTC, Emilkroldrup approved these changes

2024-05-19 11:42 UTC, Emilkroldrup commented on src/main/resources/templates/profilePage.html
Du er med på at i og med du har valgt og acceptere dine nuværrende i merge conflikten, vil denne merge fjerne alt styling og sådan, da var lavet til profile page af mig tidligere ^^ skal bare lige være sikker på du er med på du skal selv stå for at style det igen, hvis du vælger denne vej

2024-05-19 11:59 UTC, merged