chore: update nav bar to be dynamic
Emilkroldrup/MinKostPlan pull request #48
Opened 2024-05-23 10:31 UTC by Emilkroldrup

![image](https://github.com/Emilkroldrup/MinKostPlan/assets/113909369/a116b2c4-5e7f-4181-91ec-a648dbc07159)

2024-05-23 16:53 UTC, Mads505m commented on src/main/java/minkostplan/application/usecase/UserUtil.java
Seems good

2024-05-23 16:54 UTC, Mads505m commented on src/main/resources/templates/navbar.html
looks good

2024-05-23 16:54 UTC, Mads505m requested changes
Scalability, change px to %,vh or vw

2024-05-24 08:18 UTC, minkguel approved these changes

2024-05-24 08:41 UTC, merged