adding Ingridients controller and js logic, and java doc for admincon…
Emilkroldrup/MinKostPlan pull request #49
Opened 2024-05-23 16:27 UTC by Mads505m

…troller

Change some html (hidden inputfields) Used it in js and controller to connect inputs to the js and then add the inputted the data to the database, in which the function was already made.

2024-05-23 16:39 UTC, Emilkroldrup requested changes
>

2024-05-23 16:39 UTC, Emilkroldrup commented on src/main/resources/static/javascript/adminPage.js
Kan godt være jeg lidt lost her. Men giver det mening og lave alt dette i js og ikke java? da vi bliver bedømt på java code og ikke js? Js fungere godt I know, men det mere om det måske var vigtigere og mappe direkte til thymeleaf og java, i stedet for igennem et script ^^ ellers ser det sku fornuftigt ud

2024-05-23 21:28 UTC, Mads505m commented on src/main/resources/static/javascript/adminPage.js
Det rigtigt, men det var det peter allerede havde gjort

2024-05-24 06:23 UTC, Emilkroldrup commented on src/main/java/minkostplan/application/DBcontroller/user/UserRepositoryImpl.java
og ændre til user i stedet for users, laver ikke fejl nogle steder aka som i security?

2024-05-24 06:23 UTC, Emilkroldrup commented on src/main/java/minkostplan/application/UIcontroller/AdminController.java
> -        String email = auth.getName(); // get logged-in username
Helle dette statement er lavet om i en anden PR

2024-05-24 08:40 UTC, Emilkroldrup approved these changes

2024-05-24 08:48 UTC, merged